### OpenSky API

In [1]:
import requests
import json
import pandas as pd

opensky_api = "https://opensky-network.org/api/states/all"

opensky_data = requests.get(opensky_api).json()
print(json.dumps(opensky_data, indent=2))

{
  "time": 1782172393,
  "states": [
    [
      "e8027e",
      "LPE2368 ",
      "Chile",
      1782172392,
      1782172392,
      -60.7827,
      -31.4157,
      9753.6,
      false,
      204.47,
      326.91,
      0,
      null,
      9745.98,
      "0475",
      false,
      0
    ],
    [
      "50047e",
      "DWC011  ",
      "",
      1782172353,
      1782172353,
      39.0145,
      31.3068,
      12489.18,
      false,
      244.31,
      148.52,
      -0.33,
      null,
      13319.76,
      null,
      false,
      0
    ],
    [
      "a7250f",
      "N56FA   ",
      "United States",
      1782172166,
      1782172167,
      -118.4945,
      34.217,
      243.84,
      false,
      8.37,
      280.62,
      0,
      null,
      205.74,
      "0213",
      false,
      0
    ],
    [
      "a53edd",
      "GPD437  ",
      "United States",
      1782172302,
      1782172302,
      -71.3176,
      41.6228,
      312.42,
      false,
      75.2,
      159.58,
      -7.15,
      null,
      365.76,
      "5313",
      false,
      0
    ],
    [
      "a47551",
      "N387AF  ",
      "United States",
      1782172392,
      1782172392,
      -112.3133,
      40.6248,
      1897.38,
      false,
      33.91,
      189.61,
      -0.33,
      null,
      1958.34,
      null,
      false,
      0
    ],
    [
      "ab6fdd",
      "AAL1626 ",
      "United States",
      1782172393,
      1782172393,
      -77.765,
      38.9568,
      7292.34,
      false,
      205.28,
      253.7,
      6.83,
      null,
      7650.48,
      "2457",
      false,
      0
    ],
    [
      "801645",
      "",
      "India",
      1782172374,
      1782172374,
      77.0889,
      28.559,
      null,
      true,
      0,
      278.44,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "a5953a",
      "TRF559  ",
      "United States",
      1782172392,
      1782172392,
      -95.1732,
      30.2617,
      525.78,
      false,
      37.68,
      145.01,
      0.98,
      null,
      541.02,
      null,
      false,
      0
    ],
    [
      "a4d86a",
      "LXJ411  ",
      "United States",
      1782172392,
      1782172392,
      -108.3925,
      37.6416,
      11277.6,
      false,
      219.98,
      350.71,
      0,
      null,
      11894.82,
      null,
      false,
      0
    ],
    [
      "80163d",
      "IGO605V ",
      "India",
      1782172327,
      1782172327,
      77.1139,
      28.5662,
      null,
      true,
      3.6,
      194.06,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "801648",
      "IGO1409 ",
      "India",
      1782172390,
      1782172392,
      76.7475,
      14.27,
      10660.38,
      false,
      235.1,
      103.15,
      0,
      null,
      11308.08,
      null,
      false,
      0
    ],
    [
      "a53eef",
      "UPS9771 ",
      "United States",
      1782172392,
      1782172392,
      -81.3254,
      33.8213,
      10363.2,
      false,
      240.39,
      261.38,
      0,
      null,
      10980.42,
      null,
      false,
      0
    ],
    [
      "c81bce",
      "SKL1    ",
      "New Zealand",
      1782172392,
      1782172392,
      170.2608,
      -45.8229,
      1973.58,
      false,
      117.59,
      227.3,
      -7.8,
      null,
      2011.68,
      null,
      false,
      0
    ],
    [
      "ac4963",
      "DAL717  ",
      "United States",
      1782172391,
      1782172391,
      -99.4055,
      39.4,
      10668,
      false,
      259.29,
      90.45,
      0,
      null,
      11148.06,
      null,
      false,
      0
    ],
    [
      "a36898",
      "DAL1736 ",
      "United States",
      1782172392,
      1782172392,
      -84.9722,
      32.0818,
      8122.92,
      false,
      218.6,
      203.73,
      3.58,
      null,
      8610.6,
      "2067",
      false,
      0
    ],
    [
      "acdfa3",
      "ASA517  ",
      "United States",
      1782172392,
      1782172392,
      -84.8028,
      27.8075,
      10363.2,
      false,
      237.3,
      280.87,
      0,
      null,
      11026.14,
      "5556",
      false,
      0
    ],
    [
      "c047e7",
      "CGBFY   ",
      "Canada",
      1782172392,
      1782172392,
      -80.3708,
      43.7759,
      2727.96,
      false,
      60.74,
      27.22,
      -0.33,
      null,
      2758.44,
      "5754",
      false,
      0
    ],
    [
      "a23563",
      "N241TD  ",
      "United States",
      1782172389,
      1782172389,
      -116.7497,
      32.9442,
      1424.94,
      false,
      47.34,
      91.25,
      0,
      null,
      1447.8,
      "0372",
      false,
      0
    ],
    [
      "abacb6",
      "SCX1836 ",
      "United States",
      1782172392,
      1782172392,
      -98.3372,
      29.6745,
      2948.94,
      false,
      157.28,
      356.06,
      11.7,
      null,
      3116.58,
      null,
      false,
      0
    ],
    [
      "801621",
      "IGO207W ",
      "India",
      1782172382,
      1782172388,
      77.0891,
      28.5605,
      null,
      true,
      0,
      216.56,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "a1befc",
      "        ",
      "United States",
      1782172249,
      1782172249,
      -104.6635,
      39.8598,
      null,
      true,
      11.32,
      180,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "ab165c",
      "N813V   ",
      "United States",
      1782172290,
      1782172355,
      -63.1799,
      49.0051,
      12192,
      false,
      227.72,
      224.63,
      -0.33,
      null,
      12374.88,
      "0745",
      false,
      0
    ],
    [
      "801622",
      "IGO54M  ",
      "India",
      1782172392,
      1782172392,
      74.8124,
      14.3925,
      11277.6,
      false,
      228.92,
      153.43,
      0,
      null,
      11955.78,
      null,
      false,
      0
    ],
    [
      "851914",
      "JAL625  ",
      "Japan",
      1782172392,
      1782172392,
      136.1595,
      35.0708,
      9136.38,
      false,
      196.54,
      258.98,
      0,
      null,
      9608.82,
      "1774",
      false,
      0
    ],
    [
      "a15bf8",
      "N187PF  ",
      "United States",
      1782172367,
      1782172367,
      -158.0812,
      21.2988,
      53.34,
      false,
      26.44,
      52.91,
      -2.28,
      null,
      76.2,
      null,
      false,
      0
    ],
    [
      "a5e550",
      "N4793F  ",
      "United States",
      1782172392,
      1782172392,
      -123.2,
      48.1848,
      1584.96,
      false,
      55.41,
      58.67,
      2.6,
      null,
      1630.68,
      null,
      false,
      0
    ],
    [
      "ad5622",
      "AMX940  ",
      "United States",
      1782172392,
      1782172392,
      -100.1965,
      25.8276,
      914.4,
      false,
      89.29,
      120.85,
      -4.88,
      null,
      937.26,
      null,
      false,
      0
    ],
    [
      "80161c",
      "AXB135  ",
      "India",
      1782172146,
      1782172146,
      65.8278,
      22.9614,
      10972.8,
      false,
      237.16,
      269.88,
      0,
      null,
      11689.08,
      null,
      false,
      0
    ],
    [
      "ad5623",
      "AAL2144 ",
      "United States",
      1782172392,
      1782172392,
      -106.8923,
      42.5967,
      11277.6,
      false,
      262.04,
      130.38,
      -0.33,
      null,
      11742.42,
      null,
      false,
      0
    ],
    [
      "ab0347",
      "N80896  ",
      "United States",
      1782172121,
      1782172189,
      -97.8119,
      33.1626,
      579.12,
      false,
      45.81,
      358.07,
      -2.28,
      null,
      571.5,
      null,
      false,
      0
    ],
    [
      "c047d8",
      "CGBFJ   ",
      "Canada",
      1782172392,
      1782172392,
      -79.6718,
      44.7342,
      1706.88,
      false,
      53.84,
      44.23,
      0.65,
      null,
      1699.26,
      "1200",
      false,
      0
    ],
    [
      "801625",
      "AIC2385 ",
      "India",
      1782172391,
      1782172391,
      100.2704,
      6.1937,
      10363.2,
      false,
      236.27,
      329.08,
      0,
      null,
      11010.9,
      null,
      false,
      0
    ],
    [
      "a23578",
      "N241U   ",
      "United States",
      1782172392,
      1782172392,
      -97.0573,
      32.3925,
      906.78,
      false,
      45.32,
      177.4,
      -0.65,
      null,
      944.88,
      null,
      false,
      0
    ],
    [
      "ad5628",
      "DAL2193 ",
      "United States",
      1782172391,
      1782172392,
      -81.2096,
      33.9418,
      693.42,
      false,
      117.54,
      240.07,
      5.85,
      null,
      723.9,
      null,
      false,
      0
    ],
    [
      "a89eb9",
      "N65453  ",
      "United States",
      1782172350,
      1782172350,
      -93.0961,
      45.4411,
      548.64,
      false,
      45.39,
      23.37,
      1.3,
      null,
      594.36,
      null,
      false,
      0
    ],
    [
      "a9a0f9",
      "N7198N  ",
      "United States",
      1782172392,
      1782172392,
      -121.3975,
      38.6534,
      144.78,
      false,
      26.36,
      174.4,
      3.25,
      null,
      91.44,
      null,
      false,
      0
    ],
    [
      "407a05",
      "EZY2862 ",
      "United Kingdom",
      1782172392,
      1782172392,
      3.6292,
      49.4712,
      11574.78,
      false,
      228,
      296.1,
      -0.33,
      null,
      12199.62,
      "3572",
      false,
      0
    ],
    [
      "ad694c",
      "SWA2693 ",
      "United States",
      1782172387,
      1782172392,
      -77.6859,
      43.1069,
      null,
      true,
      0,
      213.75,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "aa4fc9",
      "N7635W  ",
      "United States",
      1782172392,
      1782172392,
      -84.9541,
      33.8475,
      998.22,
      false,
      38.4,
      219.02,
      -0.98,
      null,
      1051.56,
      null,
      false,
      0
    ],
    [
      "c047cf",
      "CGBFA   ",
      "Canada",
      1782172392,
      1782172392,
      -79.8595,
      43.7499,
      388.62,
      false,
      38.59,
      132.84,
      2.93,
      null,
      365.76,
      "1200",
      false,
      0
    ],
    [
      "8a02d6",
      "GIA824  ",
      "Indonesia",
      1782172392,
      1782172392,
      104.417,
      -1.0596,
      11582.4,
      false,
      233.01,
      337.68,
      0.33,
      null,
      12313.92,
      null,
      false,
      0
    ],
    [
      "aad012",
      "UAL194  ",
      "United States",
      1782172392,
      1782172392,
      -105.8627,
      51.5205,
      10058.4,
      false,
      263.14,
      38.01,
      0,
      null,
      10142.22,
      null,
      false,
      0
    ],
    [
      "8a02d4",
      "GIA207  ",
      "Indonesia",
      1782172390,
      1782172390,
      110.116,
      -7.7243,
      4221.48,
      false,
      143.97,
      338.84,
      15.93,
      null,
      4472.94,
      null,
      false,
      0
    ],
    [
      "ae6305",
      "HAWK294 ",
      "United States",
      1782172179,
      1782172179,
      -97.8048,
      27.5021,
      null,
      true,
      14.92,
      132.19,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "7c7268",
      "WVU     ",
      "Australia",
      1782172392,
      1782172392,
      144.7493,
      -37.9217,
      190.5,
      false,
      48.88,
      1.21,
      -0.98,
      null,
      304.8,
      "1200",
      false,
      0
    ],
    [
      "4bc8c8",
      "PGT390  ",
      "Turkey",
      1782172392,
      1782172392,
      22.5865,
      51.2341,
      10363.2,
      false,
      229.28,
      9.17,
      0,
      null,
      10782.3,
      "4430",
      false,
      0
    ],
    [
      "4bc8c4",
      "PGT698  ",
      "Turkey",
      1782172243,
      1782172243,
      31.9404,
      28.388,
      10668,
      false,
      238.14,
      164.46,
      0,
      null,
      11407.14,
      "3340",
      false,
      0
    ],
    [
      "4bc8c2",
      "PGT1458 ",
      "Turkey",
      1782172392,
      1782172392,
      23.63,
      42.0934,
      10363.2,
      false,
      233.35,
      350.99,
      0,
      null,
      10911.84,
      "5306",
      false,
      0
    ],
    [
      "ab0361",
      "AAL1985 ",
      "United States",
      1782172383,
      1782172390,
      -77.0408,
      38.8542,
      null,
      true,
      0,
      267.19,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "abf008",
      "SWA4558 ",
      "United States",
      1782172392,
      1782172392,
      -82.1451,
      29.7386,
      7627.62,
      false,
      224.04,
      170.08,
      0.33,
      null,
      8100.06,
      "7233",
      false,
      0
    ],
    [
      "801696",
      "VJI563  ",
      "India",
      1782172392,
      1782172392,
      76.9277,
      24.7939,
      12496.8,
      false,
      232.02,
      179.62,
      0.33,
      null,
      13274.04,
      null,
      false,
      0
    ],
    [
      "4bc8d9",
      "PGT604  ",
      "Turkey",
      1782172213,
      1782172263,
      51.6055,
      25.2605,
      null,
      true,
      4.63,
      67.5,
      null,
      null,
      null,
      "5177",
      false,
      0
    ],
    [
      "841a6c",
      "ADO100  ",
      "Japan",
      1782172392,
      1782172392,
      141.099,
      38.351,
      2118.36,
      false,
      137.01,
      140.33,
      -8.78,
      null,
      2148.84,
      null,
      false,
      0
    ],
    [
      "a4d838",
      "DAL58   ",
      "United States",
      1782172392,
      1782172392,
      -70.3513,
      43.1583,
      6073.14,
      false,
      215.43,
      61.78,
      7.15,
      null,
      6278.88,
      "1324",
      false,
      0
    ],
    [
      "ac234a",
      "N881TW  ",
      "United States",
      1782172392,
      1782172392,
      -155.3808,
      62.8762,
      1950.72,
      false,
      88.94,
      111.37,
      7.15,
      null,
      2011.68,
      null,
      false,
      0
    ],
    [
      "a2226b",
      "GAQV    ",
      "United States",
      1782172391,
      1782172392,
      -123.677,
      49.0177,
      975.36,
      false,
      46.7,
      130.53,
      3.58,
      null,
      1051.56,
      null,
      false,
      0
    ],
    [
      "ac234f",
      "UAL1602 ",
      "United States",
      1782172323,
      1782172390,
      -97.0348,
      32.9091,
      null,
      true,
      8.75,
      270,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "a35592",
      "JBU81   ",
      "United States",
      1782172392,
      1782172392,
      -79.2369,
      43.0216,
      9753.6,
      false,
      204.78,
      290.44,
      0,
      null,
      10096.5,
      "3371",
      false,
      0
    ],
    [
      "ad5679",
      "DAL3021 ",
      "United States",
      1782172192,
      1782172197,
      -84.4415,
      33.64,
      null,
      true,
      1.29,
      303.75,
      null,
      null,
      null,
      null,
      false,
      0
    ],
    [
      "a5f834",
      "N484HR  ",
      "United States",
      1782172392,
      1782172392,
      -119.1034,
      34.227,
      312.42,
      false,
      57.17,
      137.55,
      0.65,
      null,
      281.94,
      null,
      false,
      0
    ],
    [
      "471efb",
      "WMT286  ",
      "Hungary",
      1782172276,
      1782172276,
      18.7619,
      42.2532,
      5334,
      false,
      193.68,
      130.8,
      -9.43,
      null,
      5676.9,
      "0246",
      false,
      0
    ],
    [
      "acdffc",
      "DAL1987 ",
      "United States",
      1782172393,
      1782172393,
      -79.9877,
      26.9224,
      10416.54,
      false,
      238.07,
      352.68,
      4.55,
      null,
      11087.1,
      "6730",
      false,
      0
    ],
    [
      "47b217",
      "IGO81Q  ",
      "Norway",
      1782172392,
      1782172392,
      72.4918,
      18.9677,
      2689.86,
      false,
      168.7,
      244.92,
      5.53,
      null,
      2705.1,
      null,
      false,
      0
    ],
    [
      "471eff",
      "WZZ411  ",
      "Hungary",
      1782172392,
      1782172392,
      12.8828,
      47.0431,
      10972.8,
      false,
      241.33,
      239.94,
      0,
      null,
      11529.06,
      "1000",
      false,
      0
    ],
    [
      "801665",
      "AIC102  ",
      "India",
      1782172392,
      1782172392,
      19.1663,
      46.6444,
      11887.2,
      false,
      255.88,
      119.24,
      0.33,
      null,
      12374.88,
      "2210",
      false,
      0
    ],
    [
      "a34268",
      "SKW3822 ",
      "United States",
      1782172392,
      1782172392,
      -121.6361,
      37.1946,
      3695.7,
      false,
      173.37,
      137.89,
      10.08,
      null,
      3878.58,
      null,
      false,
      0
    ],
    [
      "8744d4",
      "ANA761  ",
      "Japan",
      1782172379,
      1782172379,
      133.5139,
      33.4871,
      9144,
      false,
      235.73,
      225.53,
      -0.33,
      null,
      9692.64,
      null,
      false,
      0
    ],
    [
      "80165e",
      "AXB1686 ",
      "India",
      1782172392,
      1782172392,
      75.6346,
      27.9093,
      11277.6,
      false,
      238.36,
      19.41,
      0,
      null,
      11978.64,
      null,
      false,
      0
    ],
    [
      "801669",
      "IGO775E ",
      "India",
      1782172095,
      1782172099,
      77.0115,
      24.758,
      11277.6,
      false,
      239.29,
      152.61,
      0,
      null,
      11986.26,
      null,
      false,
      0
    ],
    [
      "7c1be6",
      "FSO     ",
      "Australia",
      1782172355,
      1782172374,
      148.5285,
      -35.1791,
      2933.7,
      false,
      81.8,
      270.72,
      0,
      null,
      3055.62,
      null,
      false,
      0
    ],
    [
      "a3689e",
      "DAL303  ",
      "United States",
      1782172392,
      1782172392,
      -85.3319,
      39.0989,
      11277.6,
      false,
      270.11,
      47.16,
      -0.33,
      null,
      11826.24,
      "1507",
      false,
      0
    ],
    [
      "a3556f",
      "JBU2602 ",
      "United States",
      1782172095,
      1782172316,
      -71.9428,
      37.3974,
      9144,
      false,
      240.42,
      2.21,
      0,
      null,
      9646.92,
      null,
      false,
      0
    ],
    [
      "abf025",
      "SWA2861 ",
      "United States",
      1782172378,
      1782172385,
      -99.7233,
      39.0044,
      10363.2,
      false,
      215.28,
      246.93,
      0,
      null,
      10850.88,
      "3255",
      false,
      0
    ],
    [
      "a53ee2",
      "UAL2413 ",
      "United States",
      1782172387,
      1782172390,
      -114.4439,
      38.2474,
      10355.58,
      false,
      220.55,
      281.57,
      0,
      null,
      10949.94,
      null,
      false,
      0
    ],
    [
      "aa8075",
      "ENY3410 ",
      "United States",
      1782172392,
      1782172392,
      -87.5134,
      42.58,
      3200.4,
      false,
      189.05,
      177.04,
      -8.45,
      null,
      3299.46,
      null,
      false,
      0
    ],
    [
      "adda1e",
      "AAL3196 ",
      "United States",
      1782172392,
      1782172392,
      -75.67,
      37.0193,
      10972.8,
      false,
      225.1,
      212.02,
      0,
      null,
      11605.26,
      "1621",
      false,
      0
    ],
    [
      "abad94",
      "SWA3633 ",
      "United States",
      1782172392,
      1782172392,
      -97.7717,
      30.4675,
      1706.88,
      false,
      120.42,
      118.86,
      -7.48,
      null,
      1798.32,
      null,
      false,
      0
    ],
    [

In [2]:
opensky_columns = [
    "icao24",
    "callsign",
    "origin_country",
    "time_position",
    "last_contact",
    "longitude",
    "latitude",
    "baro_altitude",
    "on_ground",
    "velocity",
    "true_track",
    "vertical_rate",
    "sensors",
    "geo_altitude",
    "squawk",
    "spi",
    "position_source",
]

opensky_df = pd.DataFrame(opensky_data["states"], columns=opensky_columns)

# print(opensky_df[
#     [
#         "icao24",
#         "callsign",
#         "latitude",
#         "longitude",
#         "baro_altitude",
#         "velocity",
#         "true_track",
#         "vertical_rate",
#     ]
# ].head())

print(opensky_df.head())
# print(opensky_df['callsign'].head(10))

   icao24  callsign origin_country  time_position  last_contact  longitude  \
0  e8027e  LPE2368           Chile   1.782172e+09    1782172392   -60.7827
1  50047e  DWC011                    1.782172e+09    1782172353    39.0145
2  a7250f  N56FA     United States   1.782172e+09    1782172167  -118.4945
3  a53edd  GPD437    United States   1.782172e+09    1782172302   -71.3176
4  a47551  N387AF    United States   1.782172e+09    1782172392  -112.3133

   latitude  baro_altitude  on_ground  velocity  true_track  vertical_rate  \
0  -31.4157        9753.60      False    204.47      326.91           0.00
1   31.3068       12489.18      False    244.31      148.52          -0.33
2   34.2170         243.84      False      8.37      280.62           0.00
3   41.6228         312.42      False     75.20      159.58          -7.15
4   40.6248        1897.38      False     33.91      189.61          -0.33

  sensors  geo_altitude squawk    spi  position_source
0    None       9745.98   0475  False                0
1    None      13319.76    NaN  False                0
2    None        205.74   0213  False                0
3    None        365.76   5313  False                0
4    None       1958.34    NaN  False                0

In [3]:
opensky_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8756 entries, 0 to 8755
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   icao24           8756 non-null   str
 1   callsign         8756 non-null   str
 2   origin_country   8756 non-null   str
 3   time_position    8676 non-null   float64
 4   last_contact     8756 non-null   int64
 5   longitude        8676 non-null   float64
 6   latitude         8676 non-null   float64
 7   baro_altitude    7755 non-null   float64
 8   on_ground        8756 non-null   bool
 9   velocity         8750 non-null   float64
 10  true_track       8756 non-null   float64
 11  vertical_rate    7788 non-null   float64
 12  sensors          0 non-null      object
 13  geo_altitude     7700 non-null   float64
 14  squawk           4007 non-null   str
 15  spi              8756 non-null   bool
 16  position_source  8756 non-null   int64
dtypes: bool(2), float64(8), int64(2), object(1), str(4)
memory usage: 1.0+ MB

### METAR API

In [4]:
metar_api = "https://aviationweather.gov/api/data/metar"

params = {
    "ids": "KJFK,KLGA,KEWR", # Important
    "format": "json"
}

metar_data = requests.get(metar_api, params=params).json()

print(json.dumps(metar_data, indent=2))

[
  {
    "icaoId": "KEWR",
    "receiptTime": "2026-06-22T23:18:44.060Z",
    "obsTime": 1782170100,
    "reportTime": "2026-06-22T23:15:00.000Z",
    "temp": 21.1,
    "dewp": 20.6,
    "wdir": 60,
    "wspd": 4,
    "visib": 4,
    "altim": 1012.3,
    "qcField": 12,
    "wxString": "-RA BR",
    "precip": 0.02,
    "metarType": "SPECI",
    "rawOb": "SPECI KEWR 222315Z 06004KT 4SM -RA BR BKN007 BKN030 OVC085 21/21 A2989 RMK AO2 P0002 T02110206 $",
    "lat": 40.6828,
    "lon": -74.1692,
    "elev": 2,
    "name": "Newark Intl, NJ, US",
    "cover": "OVC",
    "clouds": [
      {
        "cover": "BKN",
        "base": 700
      },
      {
        "cover": "BKN",
        "base": 3000
      },
      {
        "cover": "OVC",
        "base": 8500
      }
    ],
    "fltCat": "IFR"
  },
  {
    "icaoId": "KJFK",
    "receiptTime": "2026-06-22T22:58:35.859Z",
    "obsTime": 1782168660,
    "reportTime": "2026-06-22T23:00:00.000Z",
    "temp": 21.7,
    "dewp": 20,
    "wdir": 180,
    "wspd": 12,
    "visib": 6,
    "altim": 1013,
    "slp": 1012.8,
    "qcField": 0,
    "wxString": "-RA BR",
    "precip": 0.03,
    "metarType": "METAR",
    "rawOb": "METAR KJFK 222251Z 18012KT 6SM -RA BR SCT009 BKN065 BKN110 OVC140 22/20 A2991 RMK RAB29 SLP128 P0003 T02170200",
    "lat": 40.6392,
    "lon": -73.7639,
    "elev": 3,
    "name": "New York/JF Kennedy Intl, NY, US",
    "cover": "OVC",
    "clouds": [
      {
        "cover": "SCT",
        "base": 900
      },
      {
        "cover": "BKN",
        "base": 6500
      },
      {
        "cover": "BKN",
        "base": 11000
      },
      {
        "cover": "OVC",
        "base": 14000
      }
    ],
    "fltCat": "VFR"
  },
  {
    "icaoId": "KLGA",
    "receiptTime": "2026-06-22T22:56:22.746Z",
    "obsTime": 1782168660,
    "reportTime": "2026-06-22T23:00:00.000Z",
    "temp": 19.4,
    "dewp": 18.9,
    "wdir": 40,
    "wspd": 7,
    "visib": 2,
    "altim": 1012.6,
    "slp": 1012.4,
    "qcField": 12,
    "wxString": "-RA BR",
    "precip": 0.005,
    "metarType": "METAR",
    "rawOb": "METAR KLGA 222251Z 04007KT 2SM -RA BR BKN007 BKN009 OVC015 19/19 A2990 RMK AO2 SFC VIS 4 RAE03B26 SLP124 P0000 T01940189 $",
    "lat": 40.7794,
    "lon": -73.8803,
    "elev": 9,
    "name": "New York/La Guardia Arpt, NY, US",
    "cover": "OVC",
    "clouds": [
      {
        "cover": "BKN",
        "base": 700
      },
      {
        "cover": "BKN",
        "base": 900
      },
      {
        "cover": "OVC",
        "base": 1500
      }
    ],
    "fltCat": "IFR"
  }
]

In [5]:
metar_df = pd.DataFrame(metar_data)

print(metar_df.columns.tolist(), '\n')
print(metar_df.shape, '\n')
print(metar_df.head())

['icaoId', 'receiptTime', 'obsTime', 'reportTime', 'temp', 'dewp', 'wdir', 'wspd', 'visib', 'altim', 'qcField', 'wxString', 'precip', 'metarType', 'rawOb', 'lat', 'lon', 'elev', 'name', 'cover', 'clouds', 'fltCat', 'slp']

(3, 23)

  icaoId               receiptTime     obsTime                reportTime  \
0   KEWR  2026-06-22T23:18:44.060Z  1782170100  2026-06-22T23:15:00.000Z
1   KJFK  2026-06-22T22:58:35.859Z  1782168660  2026-06-22T23:00:00.000Z
2   KLGA  2026-06-22T22:56:22.746Z  1782168660  2026-06-22T23:00:00.000Z

   temp  dewp  wdir  wspd  visib   altim  ...  metarType  \
0  21.1  20.6    60     4      4  1012.3  ...      SPECI
1  21.7  20.0   180    12      6  1013.0  ...      METAR
2  19.4  18.9    40     7      2  1012.6  ...      METAR

                                               rawOb      lat      lon elev  \
0  SPECI KEWR 222315Z 06004KT 4SM -RA BR BKN007 B...  40.6828 -74.1692    2
1  METAR KJFK 222251Z 18012KT 6SM -RA BR SCT009 B...  40.6392 -73.7639    3
2  METAR KLGA 222251Z 04007KT 2SM -RA BR BKN007 B...  40.7794 -73.8803    9

                               name  cover  \
0               Newark Intl, NJ, US    OVC
1  New York/JF Kennedy Intl, NY, US    OVC
2  New York/La Guardia Arpt, NY, US    OVC

                                              clouds fltCat     slp
0  [{'cover': 'BKN', 'base': 700}, {'cover': 'BKN...    IFR     NaN
1  [{'cover': 'SCT', 'base': 900}, {'cover': 'BKN...    VFR  1012.8
2  [{'cover': 'BKN', 'base': 700}, {'cover': 'BKN...    IFR  1012.4

[3 rows x 23 columns]

In [6]:
print(metar_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   icaoId       3 non-null      str
 1   receiptTime  3 non-null      str
 2   obsTime      3 non-null      int64
 3   reportTime   3 non-null      str
 4   temp         3 non-null      float64
 5   dewp         3 non-null      float64
 6   wdir         3 non-null      int64
 7   wspd         3 non-null      int64
 8   visib        3 non-null      int64
 9   altim        3 non-null      float64
 10  qcField      3 non-null      int64
 11  wxString     3 non-null      str
 12  precip       3 non-null      float64
 13  metarType    3 non-null      str
 14  rawOb        3 non-null      str
 15  lat          3 non-null      float64
 16  lon          3 non-null      float64
 17  elev         3 non-null      int64
 18  name         3 non-null      str
 19  cover        3 non-null      str
 20  clouds       3 non-null      object
 21  fltCat       3 non-null      str
 22  slp          2 non-null      float64
dtypes: float64(7), int64(6), object(1), str(9)
memory usage: 684.0+ bytes
None

### SIGMET API

In [7]:
sigmet_api = "https://aviationweather.gov/api/data/airsigmet"

params = {
    "format": "json"
}

sigmet_data = requests.get(sigmet_api, params=params).json()

print(json.dumps(sigmet_data, indent=2))

[
  {
    "icaoId": "KKCI",
    "alphaChar": "W",
    "seriesId": "43W",
    "receiptTime": "2026-06-22T22:54:56.620Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 45000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 270,
    "movementSpd": 35,
    "rawAirSigmet": "WSUS33 KKCI 222255\nSIGW \nCONVECTIVE SIGMET 43W\nVALID UNTIL 0055Z\nMT WY\nFROM 20SW MLS-20E SHR-30W SHR-40ENE BIL-20SW MLS\nAREA SEV TS MOV FROM 27035KT. TOPS TO FL450.\nHAIL TO 1 IN...WIND GUSTS TO 50KT POSS.\n\nOUTLOOK VALID 230055-230455\nFROM 50NNW GGW-DBL-40S MLP-40N FCA-50NNW GGW\nWST ISSUANCES POSS. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 46.144,
        "lon": -106.289
      },
      {
        "lat": 44.839,
        "lon": -106.591
      },
      {
        "lat": 44.838,
        "lon": -107.769
      },
      {
        "lat": 46.061,
        "lon": -107.745
      },
      {
        "lat": 46.144,
        "lon": -106.289
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "E",
    "seriesId": "83E",
    "receiptTime": "2026-06-22T22:54:58.745Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 250,
    "movementSpd": 30,
    "rawAirSigmet": "WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 83E\nVALID UNTIL 0055Z\nNY NJ PA DE MD VA NC DC WV SC OH TN KY AND DE NJ NY CT CSTL WTRS\nFROM 20N JFK-40S HTO-20N IRQ-10WNW VXV-40NNE HNN-30N JST-20N JFK\nAREA SEV TS MOV FROM 25030KT. TOPS ABV FL450.\nTORNADOES...HAIL TO 1 IN...WIND GUSTS TO 60KT POSS.\n\nOUTLOOK VALID 230055-230455\nFROM SYR-BOS-150SE SIE-190ESE ECG-150SSE ILM-160SE MIA-80WSW\nEYW-100W PIE-200S CEW-40ESE PXV-SYR\nREF WW 374 375.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 40.962,
        "lon": -73.77
      },
      {
        "lat": 40.255,
        "lon": -72.32
      },
      {
        "lat": 34.042,
        "lon": -82.16
      },
      {
        "lat": 35.965,
        "lon": -84.085
      },
      {
        "lat": 39.364,
        "lon": -81.701
      },
      {
        "lat": 40.823,
        "lon": -78.83
      },
      {
        "lat": 40.962,
        "lon": -73.77
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "E",
    "seriesId": "84E",
    "receiptTime": "2026-06-22T22:54:58.770Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 280,
    "movementSpd": 30,
    "rawAirSigmet": "WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 84E\nVALID UNTIL 0055Z\nNC GA TN AL\nFROM 40ENE BNA-20W ODF-30NE VUZ-30SSW BNA-40ENE BNA\nAREA SEV TS MOV FROM 28030KT. TOPS ABV FL450.\nTORNADOES...HAIL TO 1 IN...WIND GUSTS TO 65KT POSS.\n\nOUTLOOK VALID 230055-230455\nFROM SYR-BOS-150SE SIE-190ESE ECG-150SSE ILM-160SE MIA-80WSW\nEYW-100W PIE-200S CEW-40ESE PXV-SYR\nREF WW 374 375.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 36.392,
        "lon": -85.917
      },
      {
        "lat": 34.699,
        "lon": -83.704
      },
      {
        "lat": 34.025,
        "lon": -86.471
      },
      {
        "lat": 35.675,
        "lon": -86.917
      },
      {
        "lat": 36.392,
        "lon": -85.917
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "E",
    "seriesId": "85E",
    "receiptTime": "2026-06-22T22:54:58.790Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 250,
    "movementSpd": 25,
    "rawAirSigmet": "WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 85E\nVALID UNTIL 0055Z\nGA\nFROM 40NNE ATL-40SSE IRQ-60WNW SAV-20N LGC-40NNE ATL\nAREA TS MOV FROM 25025KT. TOPS ABV FL450.\n\nOUTLOOK VALID 230055-230455\nFROM SYR-BOS-150SE SIE-190ESE ECG-150SSE ILM-160SE MIA-80WSW\nEYW-100W PIE-200S CEW-40ESE PXV-SYR\nREF WW 374 375.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 34.244,
        "lon": -84.132
      },
      {
        "lat": 33.095,
        "lon": -81.856
      },
      {
        "lat": 32.537,
        "lon": -82.203
      },
      {
        "lat": 33.382,
        "lon": -85.21
      },
      {
        "lat": 34.244,
        "lon": -84.132
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "E",
    "seriesId": "86E",
    "receiptTime": "2026-06-22T22:54:58.814Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 250,
    "movementSpd": 20,
    "rawAirSigmet": "WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 86E\nVALID UNTIL 0055Z\nFL GA AL AND FL GA CSTL WTRS\nFROM 20ESE LGC-60SE SAV-20S CRG-20W CEW-20NE MGM-20ESE LGC\nAREA SEV TS MOV FROM 25020KT. TOPS ABV FL450.\nHAIL TO 1 IN...WIND GUSTS TO 50KT POSS.\n\nOUTLOOK VALID 230055-230455\nFROM SYR-BOS-150SE SIE-190ESE ECG-150SSE ILM-160SE MIA-80WSW\nEYW-100W PIE-200S CEW-40ESE PXV-SYR\nREF WW 374 375.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 32.922,
        "lon": -84.844
      },
      {
        "lat": 31.452,
        "lon": -80.284
      },
      {
        "lat": 30.008,
        "lon": -81.51
      },
      {
        "lat": 30.829,
        "lon": -87.067
      },
      {
        "lat": 32.455,
        "lon": -86.041
      },
      {
        "lat": 32.922,
        "lon": -84.844
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "E",
    "seriesId": "87E",
    "receiptTime": "2026-06-22T22:54:58.840Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": null,
    "movementSpd": null,
    "rawAirSigmet": "WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 87E\nVALID UNTIL 0055Z\nFL AND CSTL WTRS\nFROM 20WSW ORL-50NE PBI-20SW MIA-40S RSW-10SSE SRQ-20WSW ORL\nAREA TS MOV LTL. TOPS ABV FL450.\n\nOUTLOOK VALID 230055-230455\nFROM SYR-BOS-150SE SIE-190ESE ECG-150SSE ILM-160SE MIA-80WSW\nEYW-100W PIE-200S CEW-40ESE PXV-SYR\nREF WW 374 375.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 28.412,
        "lon": -81.689
      },
      {
        "lat": 27.269,
        "lon": -79.425
      },
      {
        "lat": 25.565,
        "lon": -80.561
      },
      {
        "lat": 25.865,
        "lon": -81.78
      },
      {
        "lat": 27.242,
        "lon": -82.477
      },
      {
        "lat": 28.412,
        "lon": -81.689
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "E",
    "seriesId": "88E",
    "receiptTime": "2026-06-22T22:54:58.867Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 28000,
    "altitudeHi2": 28000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 210,
    "movementSpd": 15,
    "rawAirSigmet": "WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 88E\nVALID UNTIL 0055Z\nME\nFROM 70NW PQI-30N PQI-20NW MLT-80SSE YQB-70NW PQI\nAREA TS MOV FROM 21015KT. TOPS TO FL280.\n\nOUTLOOK VALID 230055-230455\nFROM SYR-BOS-150SE SIE-190ESE ECG-150SSE ILM-160SE MIA-80WSW\nEYW-100W PIE-200S CEW-40ESE PXV-SYR\nREF WW 374 375.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 47.589,
        "lon": -69.314
      },
      {
        "lat": 47.273,
        "lon": -68.09
      },
      {
        "lat": 45.815,
        "lon": -68.857
      },
      {
        "lat": 45.569,
        "lon": -70.653
      },
      {
        "lat": 47.589,
        "lon": -69.314
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "C",
    "seriesId": "74C",
    "receiptTime": "2026-06-22T22:54:59.708Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 270,
    "movementSpd": 10,
    "rawAirSigmet": "WSUS32 KKCI 222255\nSIGC \nCONVECTIVE SIGMET 74C\nVALID UNTIL 0055Z\nTX\nFROM 10E MAF-60NW DLF-90SSE MRF-50SSW MRF-30E INK-10E MAF\nAREA TS MOV FROM 27010KT. TOPS ABV FL450.\n\nOUTLOOK VALID 230055-230455\nAREA 1...FROM 40E PXV-200S CEW-MRF-70SW LBB-40E PXV\nREF WW 374.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.\n\nAREA 2...FROM 50NNW GGW-70NE MOT-ONL-LBL-ALS-DBL-50NNW GGW\nREF WW 376 377.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 32.02,
        "lon": -101.979
      },
      {
        "lat": 30.063,
        "lon": -101.585
      },
      {
        "lat": 28.912,
        "lon": -103.294
      },
      {
        "lat": 29.528,
        "lon": -104.317
      },
      {
        "lat": 31.869,
        "lon": -102.648
      },
      {
        "lat": 32.02,
        "lon": -101.979
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "C",
    "seriesId": "75C",
    "receiptTime": "2026-06-22T22:54:59.736Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 280,
    "movementSpd": 30,
    "rawAirSigmet": "WSUS32 KKCI 222255\nSIGC \nCONVECTIVE SIGMET 75C\nVALID UNTIL 0055Z\nNE SD MT WY\nFROM 90SE MLS-40N RAP-40E BFF-50NNW CYS-60S MLS-90SE MLS\nAREA SEV TS MOV FROM 28030KT. TOPS ABV FL450.\nHAIL TO 3 IN...WIND GUSTS TO 60KT POSS.\n\nOUTLOOK VALID 230055-230455\nAREA 1...FROM 40E PXV-200S CEW-MRF-70SW LBB-40E PXV\nREF WW 374.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.\n\nAREA 2...FROM 50NNW GGW-70NE MOT-ONL-LBL-ALS-DBL-50NNW GGW\nREF WW 376 377.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 45.309,
        "lon": -104.442
      },
      {
        "lat": 44.645,
        "lon": -103.01
      },
      {
        "lat": 41.887,
        "lon": -102.587
      },
      {
        "lat": 41.981,
        "lon": -105.2
      },
      {
        "lat": 45.383,
        "lon": -105.95
      },
      {
        "lat": 45.309,
        "lon": -104.442
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "C",
    "seriesId": "76C",
    "receiptTime": "2026-06-22T22:54:59.766Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 290,
    "movementSpd": 25,
    "rawAirSigmet": "WSUS32 KKCI 222255\nSIGC \nCONVECTIVE SIGMET 76C\nVALID UNTIL 0055Z\nNE CO WY\nFROM 20N CYS-30N SNY-30SSW LBF-40NNW GLD-AKO-20N CYS\nAREA SEV TS MOV FROM 29025KT. TOPS ABV FL450.\nHAIL TO 1 IN...WIND GUSTS TO 50KT POSS.\n\nOUTLOOK VALID 230055-230455\nAREA 1...FROM 40E PXV-200S CEW-MRF-70SW LBB-40E PXV\nREF WW 374.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.\n\nAREA 2...FROM 50NNW GGW-70NE MOT-ONL-LBL-ALS-DBL-50NNW GGW\nREF WW 376 377.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 41.542,
        "lon": -104.77
      },
      {
        "lat": 41.603,
        "lon": -102.98
      },
      {
        "lat": 40.665,
        "lon": -100.974
      },
      {
        "lat": 40.004,
        "lon": -102.022
      },
      {
        "lat": 40.16,
        "lon": -103.18
      },
      {
        "lat": 41.542,
        "lon": -104.77
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "C",
    "seriesId": "77C",
    "receiptTime": "2026-06-22T22:54:59.795Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 45000,
    "altitudeHi2": 60000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 300,
    "movementSpd": 20,
    "rawAirSigmet": "WSUS32 KKCI 222255\nSIGC \nCONVECTIVE SIGMET 77C\nVALID UNTIL 0055Z\nCO\nFROM 40NNW PUB-40N LAA-50E TBE-20SW TBE-40NNW PUB\nAREA SEV TS MOV FROM 30020KT. TOPS ABV FL450.\nHAIL TO 1 IN...WIND GUSTS TO 50KT POSS.\n\nOUTLOOK VALID 230055-230455\nAREA 1...FROM 40E PXV-200S CEW-MRF-70SW LBB-40E PXV\nREF WW 374.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.\n\nAREA 2...FROM 50NNW GGW-70NE MOT-ONL-LBL-ALS-DBL-50NNW GGW\nREF WW 376 377.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 38.904,
        "lon": -104.757
      },
      {
        "lat": 38.865,
        "lon": -102.69
      },
      {
        "lat": 37.265,
        "lon": -102.55
      },
      {
        "lat": 37.035,
        "lon": -103.894
      },
      {
        "lat": 38.904,
        "lon": -104.757
      }
    ]
  },
  {
    "icaoId": "KKCI",
    "alphaChar": "C",
    "seriesId": "78C",
    "receiptTime": "2026-06-22T22:54:59.826Z",
    "creationTime": "2026-06-22T22:55:00.000Z",
    "validTimeFrom": 1782168900,
    "validTimeTo": 1782176100,
    "airSigmetType": "SIGMET",
    "hazard": "CONVECTIVE",
    "altitudeHi1": 42000,
    "altitudeHi2": 42000,
    "altitudeLow1": null,
    "altitudeLow2": null,
    "movementDir": 250,
    "movementSpd": 20,
    "rawAirSigmet": "WSUS32 KKCI 222255\nSIGC \nCONVECTIVE SIGMET 78C\nVALID UNTIL 0055Z\nND MT\nFROM 60NE MOT-40E MOT-40WNW DIK-50W ISN-50NNE ISN-60NE MOT\nAREA TS MOV FROM 25020KT. TOPS TO FL420.\n\nOUTLOOK VALID 230055-230455\nAREA 1...FROM 40E PXV-200S CEW-MRF-70SW LBB-40E PXV\nREF WW 374.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.\n\nAREA 2...FROM 50NNW GGW-70NE MOT-ONL-LBL-ALS-DBL-50NNW GGW\nREF WW 376 377.\nWST ISSUANCES EXPD. REFER TO MOST RECENT ACUS01 KWNS FROM STORM\nPREDICTION CENTER FOR SYNOPSIS AND METEOROLOGICAL DETAILS.",
    "postProcessFlag": 0,
    "severity": 5,
    "coords": [
      {
        "lat": 48.96,
        "lon": -100.216
      },
      {
        "lat": 48.256,
        "lon": -100.292
      },
      {
        "lat": 47.111,
        "lon": -103.672
      },
      {
        "lat": 48.173,
        "lon": -104.883
      },
      {
        "lat": 48.951,
        "lon": -103.143
      },
      {
        "lat": 48.96,
        "lon": -100.216
      }
    ]
  }
]

In [8]:
sigmet_df = pd.DataFrame(sigmet_data)

print(sigmet_df.shape)
print(sigmet_df.columns.tolist())
print(sigmet_df.head())

(12, 19)
['icaoId', 'alphaChar', 'seriesId', 'receiptTime', 'creationTime', 'validTimeFrom', 'validTimeTo', 'airSigmetType', 'hazard', 'altitudeHi1', 'altitudeHi2', 'altitudeLow1', 'altitudeLow2', 'movementDir', 'movementSpd', 'rawAirSigmet', 'postProcessFlag', 'severity', 'coords']
  icaoId alphaChar seriesId               receiptTime  \
0   KKCI         W      43W  2026-06-22T22:54:56.620Z
1   KKCI         E      83E  2026-06-22T22:54:58.745Z
2   KKCI         E      84E  2026-06-22T22:54:58.770Z
3   KKCI         E      85E  2026-06-22T22:54:58.790Z
4   KKCI         E      86E  2026-06-22T22:54:58.814Z

               creationTime  validTimeFrom  validTimeTo airSigmetType  \
0  2026-06-22T22:55:00.000Z     1782168900   1782176100        SIGMET
1  2026-06-22T22:55:00.000Z     1782168900   1782176100        SIGMET
2  2026-06-22T22:55:00.000Z     1782168900   1782176100        SIGMET
3  2026-06-22T22:55:00.000Z     1782168900   1782176100        SIGMET
4  2026-06-22T22:55:00.000Z     1782168900   1782176100        SIGMET

       hazard  altitudeHi1  altitudeHi2 altitudeLow1 altitudeLow2  \
0  CONVECTIVE        45000        45000         None         None
1  CONVECTIVE        45000        60000         None         None
2  CONVECTIVE        45000        60000         None         None
3  CONVECTIVE        45000        60000         None         None
4  CONVECTIVE        45000        60000         None         None

   movementDir  movementSpd  \
0        270.0         35.0
1        250.0         30.0
2        280.0         30.0
3        250.0         25.0
4        250.0         20.0

                                        rawAirSigmet  postProcessFlag  \
0  WSUS33 KKCI 222255\nSIGW \nCONVECTIVE SIGMET 4...                0
1  WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...                0
2  WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...                0
3  WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...                0
4  WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...                0

   severity                                             coords
0         5  [{'lat': 46.144, 'lon': -106.289}, {'lat': 44....
1         5  [{'lat': 40.962, 'lon': -73.77}, {'lat': 40.25...
2         5  [{'lat': 36.392, 'lon': -85.917}, {'lat': 34.6...
3         5  [{'lat': 34.244, 'lon': -84.132}, {'lat': 33.0...
4         5  [{'lat': 32.922, 'lon': -84.844}, {'lat': 31.4...

In [9]:
print(sigmet_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   icaoId           12 non-null     str
 1   alphaChar        12 non-null     str
 2   seriesId         12 non-null     str
 3   receiptTime      12 non-null     str
 4   creationTime     12 non-null     str
 5   validTimeFrom    12 non-null     int64
 6   validTimeTo      12 non-null     int64
 7   airSigmetType    12 non-null     str
 8   hazard           12 non-null     str
 9   altitudeHi1      12 non-null     int64
 10  altitudeHi2      12 non-null     int64
 11  altitudeLow1     0 non-null      object
 12  altitudeLow2     0 non-null      object
 13  movementDir      11 non-null     float64
 14  movementSpd      11 non-null     float64
 15  rawAirSigmet     12 non-null     str
 16  postProcessFlag  12 non-null     int64
 17  severity         12 non-null     int64
 18  coords           12 non-null     object
dtypes: float64(2), int64(6), object(3), str(8)
memory usage: 1.9+ KB
None

### TAF API

In [10]:
taf_api = "https://aviationweather.gov/api/data/taf"

params = {
    "ids": "KJFK,KLGA,KEWR", # Important
    "format": "json"
}

taf_data = requests.get(taf_api, params=params).json()

print(json.dumps(taf_data, indent=2))

[
  {
    "icaoId": "KLGA",
    "dbPopTime": "2026-06-22T23:40:05.865Z",
    "bulletinTime": "2026-06-22T23:39:00.000Z",
    "issueTime": "2026-06-22T23:39:00.000Z",
    "validTimeFrom": 1782172800,
    "validTimeTo": 1782280800,
    "rawTAF": "TAF KLGA 222339Z 2300/2406 03010KT 4SM -SHRA BR BKN007 BKN009 FM230400 18009KT 2SM -SHRA BR BKN003 TEMPO 2304/2308 1SM TSRA BR OVC003CB FM230900 20006KT 3SM -SHRA BR BKN003 PROB30 2312/2315 1SM -SHRA BR OVC002 FM231500 33008KT 4SM -SHRA BR BKN003 FM231900 35010KT 5SM -SHRA BR OVC007 FM240000 33008KT P6SM SCT070",
    "mostRecent": 1,
    "remarks": "",
    "lat": 40.77945,
    "lon": -73.88027,
    "elev": 9,
    "prior": 6,
    "name": "New York/La Guardia Arpt",
    "fcsts": [
      {
        "timeFrom": 1782172800,
        "timeTo": 1782187200,
        "timeBec": null,
        "fcstChange": null,
        "probability": null,
        "wdir": 30,
        "wspd": 10,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 4,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 700,
            "type": null
          },
          {
            "cover": "BKN",
            "base": 900,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782187200,
        "timeTo": 1782205200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 180,
        "wspd": 9,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 2,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 300,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782187200,
        "timeTo": 1782201600,
        "timeBec": null,
        "fcstChange": "TEMPO",
        "probability": null,
        "wdir": null,
        "wspd": null,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 1,
        "altim": null,
        "vertVis": null,
        "wxString": "TSRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 300,
            "type": "CB"
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782205200,
        "timeTo": 1782226800,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 200,
        "wspd": 6,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 3,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 300,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782216000,
        "timeTo": 1782226800,
        "timeBec": null,
        "fcstChange": "PROB",
        "probability": 30,
        "wdir": null,
        "wspd": null,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 1,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 200,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782226800,
        "timeTo": 1782241200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 330,
        "wspd": 8,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 4,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 300,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782241200,
        "timeTo": 1782259200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 350,
        "wspd": 10,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 5,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 700,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782259200,
        "timeTo": 1782280800,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 330,
        "wspd": 8,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": "6+",
        "altim": null,
        "vertVis": null,
        "wxString": null,
        "notDecoded": null,
        "clouds": [
          {
            "cover": "SCT",
            "base": 7000,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      }
    ]
  },
  {
    "icaoId": "KJFK",
    "dbPopTime": "2026-06-22T23:40:06.024Z",
    "bulletinTime": "2026-06-22T23:39:00.000Z",
    "issueTime": "2026-06-22T23:39:00.000Z",
    "validTimeFrom": 1782172800,
    "validTimeTo": 1782280800,
    "rawTAF": "TAF KJFK 222339Z 2300/2406 18010KT 6SM -SHRA BR SCT008 BKN015 FM230400 18009KT 2SM -SHRA BR BKN004 TEMPO 2304/2308 1SM TSRA BR OVC004CB FM230900 20006KT 3SM -SHRA BR BKN004 PROB30 2312/2315 1SM -SHRA BR OVC003 FM231500 33008KT 4SM -SHRA BR BKN004 FM231900 35010KT 5SM -SHRA BR OVC007 FM240000 33008KT P6SM SCT070",
    "mostRecent": 1,
    "remarks": "",
    "lat": 40.63916,
    "lon": -73.76394,
    "elev": 3,
    "prior": 0,
    "name": "New York/JF Kennedy Intl",
    "fcsts": [
      {
        "timeFrom": 1782172800,
        "timeTo": 1782187200,
        "timeBec": null,
        "fcstChange": null,
        "probability": null,
        "wdir": 180,
        "wspd": 10,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 6,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "SCT",
            "base": 800,
            "type": null
          },
          {
            "cover": "BKN",
            "base": 1500,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782187200,
        "timeTo": 1782205200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 180,
        "wspd": 9,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 2,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 400,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782187200,
        "timeTo": 1782201600,
        "timeBec": null,
        "fcstChange": "TEMPO",
        "probability": null,
        "wdir": null,
        "wspd": null,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 1,
        "altim": null,
        "vertVis": null,
        "wxString": "TSRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 400,
            "type": "CB"
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782205200,
        "timeTo": 1782226800,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 200,
        "wspd": 6,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 3,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 400,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782216000,
        "timeTo": 1782226800,
        "timeBec": null,
        "fcstChange": "PROB",
        "probability": 30,
        "wdir": null,
        "wspd": null,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 1,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 300,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782226800,
        "timeTo": 1782241200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 330,
        "wspd": 8,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 4,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 400,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782241200,
        "timeTo": 1782259200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 350,
        "wspd": 10,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 5,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 700,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782259200,
        "timeTo": 1782280800,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 330,
        "wspd": 8,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": "6+",
        "altim": null,
        "vertVis": null,
        "wxString": null,
        "notDecoded": null,
        "clouds": [
          {
            "cover": "SCT",
            "base": 7000,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      }
    ]
  },
  {
    "icaoId": "KEWR",
    "dbPopTime": "2026-06-22T23:40:06.276Z",
    "bulletinTime": "2026-06-22T23:39:00.000Z",
    "issueTime": "2026-06-22T23:39:00.000Z",
    "validTimeFrom": 1782172800,
    "validTimeTo": 1782280800,
    "rawTAF": "TAF KEWR 222339Z 2300/2406 07008KT 4SM -SHRA BR BKN007 FM230400 18009KT 2SM -SHRA BR BKN005 TEMPO 2304/2308 1SM TSRA BR OVC005CB FM230900 20006KT 3SM -SHRA BR BKN005 PROB30 2312/2315 1SM -SHRA BR OVC004 FM231500 33008KT 4SM -SHRA BR BKN005 FM231900 35010KT 5SM -SHRA BR OVC007 FM240000 33008KT P6SM SCT070",
    "mostRecent": 1,
    "remarks": "",
    "lat": 40.68277,
    "lon": -74.16924,
    "elev": 2,
    "prior": 5,
    "name": "Newark Intl",
    "fcsts": [
      {
        "timeFrom": 1782172800,
        "timeTo": 1782187200,
        "timeBec": null,
        "fcstChange": null,
        "probability": null,
        "wdir": 70,
        "wspd": 8,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 4,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 700,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782187200,
        "timeTo": 1782205200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 180,
        "wspd": 9,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 2,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 500,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782187200,
        "timeTo": 1782201600,
        "timeBec": null,
        "fcstChange": "TEMPO",
        "probability": null,
        "wdir": null,
        "wspd": null,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 1,
        "altim": null,
        "vertVis": null,
        "wxString": "TSRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 500,
            "type": "CB"
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782205200,
        "timeTo": 1782226800,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 200,
        "wspd": 6,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 3,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 500,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782216000,
        "timeTo": 1782226800,
        "timeBec": null,
        "fcstChange": "PROB",
        "probability": 30,
        "wdir": null,
        "wspd": null,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 1,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 400,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782226800,
        "timeTo": 1782241200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 330,
        "wspd": 8,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 4,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "BKN",
            "base": 500,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782241200,
        "timeTo": 1782259200,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 350,
        "wspd": 10,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": 5,
        "altim": null,
        "vertVis": null,
        "wxString": "-SHRA BR",
        "notDecoded": null,
        "clouds": [
          {
            "cover": "OVC",
            "base": 700,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      },
      {
        "timeFrom": 1782259200,
        "timeTo": 1782280800,
        "timeBec": null,
        "fcstChange": "FM",
        "probability": null,
        "wdir": 330,
        "wspd": 8,
        "wgst": null,
        "wshearHgt": null,
        "wshearDir": null,
        "wshearSpd": null,
        "visib": "6+",
        "altim": null,
        "vertVis": null,
        "wxString": null,
        "notDecoded": null,
        "clouds": [
          {
            "cover": "SCT",
            "base": 7000,
            "type": null
          }
        ],
        "icgTurb": [],
        "temp": []
      }
    ]
  }
]

In [11]:
taf_df = pd.DataFrame(taf_data)

print(taf_df.columns.tolist(), '\n')
print(taf_df.shape, '\n')
print(taf_df.head())

['icaoId', 'dbPopTime', 'bulletinTime', 'issueTime', 'validTimeFrom', 'validTimeTo', 'rawTAF', 'mostRecent', 'remarks', 'lat', 'lon', 'elev', 'prior', 'name', 'fcsts']

(3, 15)

  icaoId                 dbPopTime              bulletinTime  \
0   KLGA  2026-06-22T23:40:05.865Z  2026-06-22T23:39:00.000Z
1   KJFK  2026-06-22T23:40:06.024Z  2026-06-22T23:39:00.000Z
2   KEWR  2026-06-22T23:40:06.276Z  2026-06-22T23:39:00.000Z

                  issueTime  validTimeFrom  validTimeTo  \
0  2026-06-22T23:39:00.000Z     1782172800   1782280800
1  2026-06-22T23:39:00.000Z     1782172800   1782280800
2  2026-06-22T23:39:00.000Z     1782172800   1782280800

                                              rawTAF  mostRecent remarks  \
0  TAF KLGA 222339Z 2300/2406 03010KT 4SM -SHRA B...           1
1  TAF KJFK 222339Z 2300/2406 18010KT 6SM -SHRA B...           1
2  TAF KEWR 222339Z 2300/2406 07008KT 4SM -SHRA B...           1

        lat       lon  elev  prior                      name  \
0  40.77945 -73.88027     9      6  New York/La Guardia Arpt
1  40.63916 -73.76394     3      0  New York/JF Kennedy Intl
2  40.68277 -74.16924     2      5               Newark Intl

                                               fcsts
0  [{'timeFrom': 1782172800, 'timeTo': 1782187200...
1  [{'timeFrom': 1782172800, 'timeTo': 1782187200...
2  [{'timeFrom': 1782172800, 'timeTo': 1782187200...

### Measure API Refresh Frequency

In [12]:
import time
from datetime import datetime, timezone

params = {
    "ids": "KJFK,KLGA,KEWR", # Important
    "format": "json"
}

def utc(ts):
    if pd.isna(ts):
        return None
    return datetime.fromtimestamp(int(ts), tz=timezone.utc).isoformat()

def measure_refresh(name, url, params=None, extract_fn=None, iterations=5, sleep_seconds=30):
    rows = []

    for i in range(iterations):
        response = requests.get(url, params=params, timeout=30)
        print(f"\n{name} poll {i+1}")
        print("URL:", response.url)
        print("Status:", response.status_code)

        if response.status_code == 204:
            value = None
            print("No data returned")
        else:
            response.raise_for_status()
            data = response.json()
            value = extract_fn(data)
            print("Refresh field:", value)

        rows.append({
            "api": name,
            "poll_number": i + 1,
            "local_poll_time_utc": datetime.now(timezone.utc).isoformat(),
            "observed_value": value
        })

        if i < iterations - 1:
            time.sleep(sleep_seconds)

    return pd.DataFrame(rows)

In [13]:
opensky_refresh = measure_refresh(
    name="OpenSky",
    url="https://opensky-network.org/api/states/all",
    extract_fn=lambda data: data.get("time"),
    iterations=5,
    sleep_seconds=30
)

opensky_refresh["observed_time_utc"] = opensky_refresh["observed_value"].apply(utc)
opensky_refresh

OpenSky poll 1
URL: https://opensky-network.org/api/states/all
Status: 200
Refresh field: 1782172390

OpenSky poll 2
URL: https://opensky-network.org/api/states/all
Status: 200
Refresh field: 1782172431

OpenSky poll 3
URL: https://opensky-network.org/api/states/all
Status: 200
Refresh field: 1782172452

OpenSky poll 4
URL: https://opensky-network.org/api/states/all
Status: 200
Refresh field: 1782172493

OpenSky poll 5
URL: https://opensky-network.org/api/states/all
Status: 200
Refresh field: 1782172530

,api,poll_number,local_poll_time_utc,observed_value,observed_time_utc
0,OpenSky,1,2026-06-22T23:53:23.702189+00:00,1782172390,2026-06-22T23:53:10+00:00
1,OpenSky,2,2026-06-22T23:53:55.601293+00:00,1782172431,2026-06-22T23:53:51+00:00
2,OpenSky,3,2026-06-22T23:54:27.704795+00:00,1782172452,2026-06-22T23:54:12+00:00
3,OpenSky,4,2026-06-22T23:55:00.438713+00:00,1782172493,2026-06-22T23:54:53+00:00
4,OpenSky,5,2026-06-22T23:55:32.531705+00:00,1782172530,2026-06-22T23:55:30+00:00

In [14]:
metar_refresh = measure_refresh(
    name="METAR",
    url="https://aviationweather.gov/api/data/metar",
    params={"ids": "KJFK,KLGA,KEWR", "format": "json"},
    extract_fn=lambda data: [(x.get("icaoId"), x.get("obsTime"), x.get("reportTime")) for x in data],
    iterations=5,
    sleep_seconds=60
)

metar_refresh

METAR poll 1
URL: https://aviationweather.gov/api/data/metar?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KEWR', 1782172260, '2026-06-23T00:00:00.000Z'), ('KJFK', 1782172260, '2026-06-23T00:00:00.000Z'), ('KLGA', 1782168660, '2026-06-22T23:00:00.000Z')]

METAR poll 2
URL: https://aviationweather.gov/api/data/metar?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KEWR', 1782172260, '2026-06-23T00:00:00.000Z'), ('KLGA', 1782172260, '2026-06-23T00:00:00.000Z'), ('KJFK', 1782172260, '2026-06-23T00:00:00.000Z')]

METAR poll 3
URL: https://aviationweather.gov/api/data/metar?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KEWR', 1782172260, '2026-06-23T00:00:00.000Z'), ('KLGA', 1782172260, '2026-06-23T00:00:00.000Z'), ('KJFK', 1782172260, '2026-06-23T00:00:00.000Z')]

METAR poll 4
URL: https://aviationweather.gov/api/data/metar?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KEWR', 1782172260, '2026-06-23T00:00:00.000Z'), ('KLGA', 1782172260, '2026-06-23T00:00:00.000Z'), ('KJFK', 1782172260, '2026-06-23T00:00:00.000Z')]

METAR poll 5
URL: https://aviationweather.gov/api/data/metar?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KEWR', 1782172260, '2026-06-23T00:00:00.000Z'), ('KLGA', 1782172260, '2026-06-23T00:00:00.000Z'), ('KJFK', 1782172260, '2026-06-23T00:00:00.000Z')]

,api,poll_number,local_poll_time_utc,observed_value
0,METAR,1,2026-06-22T23:55:33.482793+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),..."
1,METAR,2,2026-06-22T23:56:35.012995+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),..."
2,METAR,3,2026-06-22T23:57:36.457424+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),..."
3,METAR,4,2026-06-22T23:58:37.125530+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),..."
4,METAR,5,2026-06-22T23:59:38.886457+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),..."

In [15]:
sigmet_refresh = measure_refresh(
    name="SIGMET",
    url="https://aviationweather.gov/api/data/airsigmet",
    params={"format": "json"},
    extract_fn=lambda data: [(x.get("seriesId"), x.get("creationTime"), x.get("validTimeTo")) for x in data[:5]],
    iterations=5,
    sleep_seconds=60
)

sigmet_refresh

SIGMET poll 1
URL: https://aviationweather.gov/api/data/airsigmet?format=json
Status: 200
Refresh field: [('79C', '2026-06-22T23:55:00.000Z', 1782179700), ('80C', '2026-06-22T23:55:00.000Z', 1782179700), ('81C', '2026-06-22T23:55:00.000Z', 1782179700), ('82C', '2026-06-22T23:55:00.000Z', 1782179700), ('83C', '2026-06-22T23:55:00.000Z', 1782179700)]

SIGMET poll 2
URL: https://aviationweather.gov/api/data/airsigmet?format=json
Status: 200
Refresh field: [('79C', '2026-06-22T23:55:00.000Z', 1782179700), ('80C', '2026-06-22T23:55:00.000Z', 1782179700), ('81C', '2026-06-22T23:55:00.000Z', 1782179700), ('82C', '2026-06-22T23:55:00.000Z', 1782179700), ('83C', '2026-06-22T23:55:00.000Z', 1782179700)]

SIGMET poll 3
URL: https://aviationweather.gov/api/data/airsigmet?format=json
Status: 200
Refresh field: [('79C', '2026-06-22T23:55:00.000Z', 1782179700), ('80C', '2026-06-22T23:55:00.000Z', 1782179700), ('81C', '2026-06-22T23:55:00.000Z', 1782179700), ('82C', '2026-06-22T23:55:00.000Z', 1782179700), ('83C', '2026-06-22T23:55:00.000Z', 1782179700)]

SIGMET poll 4
URL: https://aviationweather.gov/api/data/airsigmet?format=json
Status: 200
Refresh field: [('79C', '2026-06-22T23:55:00.000Z', 1782179700), ('80C', '2026-06-22T23:55:00.000Z', 1782179700), ('81C', '2026-06-22T23:55:00.000Z', 1782179700), ('82C', '2026-06-22T23:55:00.000Z', 1782179700), ('83C', '2026-06-22T23:55:00.000Z', 1782179700)]

SIGMET poll 5
URL: https://aviationweather.gov/api/data/airsigmet?format=json
Status: 200
Refresh field: [('79C', '2026-06-22T23:55:00.000Z', 1782179700), ('80C', '2026-06-22T23:55:00.000Z', 1782179700), ('81C', '2026-06-22T23:55:00.000Z', 1782179700), ('82C', '2026-06-22T23:55:00.000Z', 1782179700), ('83C', '2026-06-22T23:55:00.000Z', 1782179700)]

,api,poll_number,local_poll_time_utc,observed_value
0,SIGMET,1,2026-06-22T23:59:39.587094+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ..."
1,SIGMET,2,2026-06-23T00:00:39.966825+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ..."
2,SIGMET,3,2026-06-23T00:01:40.316070+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ..."
3,SIGMET,4,2026-06-23T00:06:31.109990+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ..."
4,SIGMET,5,2026-06-23T00:07:31.427624+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ..."

In [16]:
taf_refresh = measure_refresh(
    name="TAF",
    url="https://aviationweather.gov/api/data/taf",
    params={"ids": "KJFK,KLGA,KEWR", "format": "json"},
    extract_fn=lambda data: [(x.get("icaoId"), x.get("issueTime"), x.get("validTimeTo")) for x in data],
    iterations=5,
    sleep_seconds=60
)

taf_refresh

TAF poll 1
URL: https://aviationweather.gov/api/data/taf?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KLGA', '2026-06-22T23:39:00.000Z', 1782280800), ('KJFK', '2026-06-22T23:39:00.000Z', 1782280800), ('KEWR', '2026-06-22T23:39:00.000Z', 1782280800)]

TAF poll 2
URL: https://aviationweather.gov/api/data/taf?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KLGA', '2026-06-22T23:39:00.000Z', 1782280800), ('KJFK', '2026-06-22T23:39:00.000Z', 1782280800), ('KEWR', '2026-06-22T23:39:00.000Z', 1782280800)]

TAF poll 3
URL: https://aviationweather.gov/api/data/taf?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KLGA', '2026-06-22T23:39:00.000Z', 1782280800), ('KJFK', '2026-06-22T23:39:00.000Z', 1782280800), ('KEWR', '2026-06-22T23:39:00.000Z', 1782280800)]

TAF poll 4
URL: https://aviationweather.gov/api/data/taf?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KLGA', '2026-06-22T23:39:00.000Z', 1782280800), ('KJFK', '2026-06-22T23:39:00.000Z', 1782280800), ('KEWR', '2026-06-22T23:39:00.000Z', 1782280800)]

TAF poll 5
URL: https://aviationweather.gov/api/data/taf?ids=KJFK%2CKLGA%2CKEWR&format=json
Status: 200
Refresh field: [('KLGA', '2026-06-22T23:39:00.000Z', 1782280800), ('KJFK', '2026-06-22T23:39:00.000Z', 1782280800), ('KEWR', '2026-06-22T23:39:00.000Z', 1782280800)]

,api,poll_number,local_poll_time_utc,observed_value
0,TAF,1,2026-06-23T00:07:36.933210+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),..."
1,TAF,2,2026-06-23T00:08:37.738373+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),..."
2,TAF,3,2026-06-23T00:09:38.077823+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),..."
3,TAF,4,2026-06-23T00:10:38.427208+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),..."
4,TAF,5,2026-06-23T00:11:38.749819+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),..."

In [17]:
def summarize_refresh(df):
    return df.assign(
        changed=df["observed_value"].astype(str).ne(df["observed_value"].astype(str).shift())
    )

summarize_refresh(opensky_refresh)

,api,poll_number,local_poll_time_utc,observed_value,observed_time_utc,changed
0,OpenSky,1,2026-06-22T23:53:23.702189+00:00,1782172390,2026-06-22T23:53:10+00:00,True
1,OpenSky,2,2026-06-22T23:53:55.601293+00:00,1782172431,2026-06-22T23:53:51+00:00,True
2,OpenSky,3,2026-06-22T23:54:27.704795+00:00,1782172452,2026-06-22T23:54:12+00:00,True
3,OpenSky,4,2026-06-22T23:55:00.438713+00:00,1782172493,2026-06-22T23:54:53+00:00,True
4,OpenSky,5,2026-06-22T23:55:32.531705+00:00,1782172530,2026-06-22T23:55:30+00:00,True

In [18]:
summarize_refresh(metar_refresh)

,api,poll_number,local_poll_time_utc,observed_value,changed
0,METAR,1,2026-06-22T23:55:33.482793+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),...",True
1,METAR,2,2026-06-22T23:56:35.012995+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),...",True
2,METAR,3,2026-06-22T23:57:36.457424+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),...",False
3,METAR,4,2026-06-22T23:58:37.125530+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),...",False
4,METAR,5,2026-06-22T23:59:38.886457+00:00,"[(KEWR, 1782172260, 2026-06-23T00:00:00.000Z),...",False

In [19]:
summarize_refresh(sigmet_refresh)

,api,poll_number,local_poll_time_utc,observed_value,changed
0,SIGMET,1,2026-06-22T23:59:39.587094+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ...",True
1,SIGMET,2,2026-06-23T00:00:39.966825+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ...",False
2,SIGMET,3,2026-06-23T00:01:40.316070+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ...",False
3,SIGMET,4,2026-06-23T00:06:31.109990+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ...",False
4,SIGMET,5,2026-06-23T00:07:31.427624+00:00,"[(79C, 2026-06-22T23:55:00.000Z, 1782179700), ...",False

In [20]:
summarize_refresh(taf_refresh)

,api,poll_number,local_poll_time_utc,observed_value,changed
0,TAF,1,2026-06-23T00:07:36.933210+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),...",True
1,TAF,2,2026-06-23T00:08:37.738373+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),...",False
2,TAF,3,2026-06-23T00:09:38.077823+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),...",False
3,TAF,4,2026-06-23T00:10:38.427208+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),...",False
4,TAF,5,2026-06-23T00:11:38.749819+00:00,"[(KLGA, 2026-06-22T23:39:00.000Z, 1782280800),...",False

### Determine Which Fields Will Actually Be Used

In [21]:
# OpenSky
opensky_keep = [
    "icao24",
    "callsign",
    "longitude",
    "latitude",
    "geo_altitude",
    "velocity",
    "true_track",
    "vertical_rate",
    "on_ground",
    "last_contact",
    # Optional:
    "baro_altitude",
    "origin_country"
]

opensky_df = opensky_df[[c for c in opensky_keep if c in opensky_df.columns]]


# METAR
metar_keep = [
    "icaoId",
    "obsTime",
    "temp",
    "wdir",
    "wspd",
    "wgst",
    "visib",
    "cover",
    "clouds",
    "fltCat",
    # Optional:
    "dewp",
    "altim",
    "rawOb"
]

metar_df = metar_df[[c for c in metar_keep if c in metar_df.columns]]


# SIGMET
sigmet_keep = [
    "hazard",
    "validTimeFrom",
    "validTimeTo",
    "altitudeHi1",
    "altitudeLow1",
    "movementDir",
    "movementSpd",
    "severity",
    "coords",
    # Optional:
    "airSigmetType",
    "rawAirSigmet",
    "creationTime"
]

sigmet_df = sigmet_df[[c for c in sigmet_keep if c in sigmet_df.columns]]


# TAF
taf_keep = [
    "icaoId",
    "issueTime",
    "validTimeFrom",
    "validTimeTo",
    "fcsts",
    # Optional:
    "rawTAF",
    "mostRecent"
]

taf_df = taf_df[[c for c in taf_keep if c in taf_df.columns]]

### OpenSky Fields

| Column | Meaning |
|----------|----------|
| icao24 | Unique aircraft identifier |
| callsign | Flight callsign |
| longitude | Aircraft longitude |
| latitude | Aircraft latitude |
| geo_altitude | GPS altitude (meters) |
| velocity | Ground speed (m/s) |
| true_track | Heading/bearing (degrees) |
| vertical_rate | Climb/descent rate (m/s) |
| on_ground | Aircraft on runway/taxiway |
| last_contact | Last position update timestamp |
| baro_altitude | Barometric altitude (backup) |
| origin_country | Aircraft registration country |

In [28]:
opensky_df.head()

,icao24,callsign,longitude,latitude,geo_altitude,velocity,true_track,vertical_rate,on_ground,last_contact,baro_altitude,origin_country
0,e8027e,LPE2368,-60.7827,-31.4157,9745.98,204.47,326.91,0.00,False,1782172392,9753.60,Chile
1,50047e,DWC011,39.0145,31.3068,13319.76,244.31,148.52,-0.33,False,1782172353,12489.18,
2,a7250f,N56FA,-118.4945,34.2170,205.74,8.37,280.62,0.00,False,1782172167,243.84,United States
3,a53edd,GPD437,-71.3176,41.6228,365.76,75.20,159.58,-7.15,False,1782172302,312.42,United States
4,a47551,N387AF,-112.3133,40.6248,1958.34,33.91,189.61,-0.33,False,1782172392,1897.38,United States

### METAR Fields

| Column | Meaning |
|----------|----------|
| icaoId | Airport ICAO code |
| obsTime | Observation timestamp |
| temp | Air temperature (°C) |
| wdir | Wind direction (degrees) |
| wspd | Wind speed (knots) |
| wgst | Wind gust speed (knots) |
| visib | Visibility |
| cover | Overall cloud coverage |
| clouds | Cloud layer details |
| fltCat | Flight category (VFR/IFR/etc.) |
| dewp | Dew point temperature (°C) |
| altim | Altimeter setting |
| rawOb | Raw METAR report |

In [33]:
metar_df.head()

,icaoId,obsTime,temp,wdir,wspd,visib,cover,clouds,fltCat,dewp,altim,rawOb
0,KEWR,1782170100,21.1,60,4,4,OVC,"[{'cover': 'BKN', 'base': 700}, {'cover': 'BKN...",IFR,20.6,1012.3,SPECI KEWR 222315Z 06004KT 4SM -RA BR BKN007 B...
1,KJFK,1782168660,21.7,180,12,6,OVC,"[{'cover': 'SCT', 'base': 900}, {'cover': 'BKN...",VFR,20.0,1013.0,METAR KJFK 222251Z 18012KT 6SM -RA BR SCT009 B...
2,KLGA,1782168660,19.4,40,7,2,OVC,"[{'cover': 'BKN', 'base': 700}, {'cover': 'BKN...",IFR,18.9,1012.6,METAR KLGA 222251Z 04007KT 2SM -RA BR BKN007 B...

In [38]:
metar_df["clouds"].iloc[0]

[{'cover': 'BKN', 'base': 700},
 {'cover': 'BKN', 'base': 3000},
 {'cover': 'OVC', 'base': 8500}]

In [39]:
pd.json_normalize(metar_df["clouds"].iloc[0])

  cover  base
0   BKN   700
1   BKN  3000
2   OVC  8500

In [ ]:
metar_clouds_df = (
    metar_df[["icaoId", "obsTime", "clouds"]]
    .explode("clouds")
    .reset_index(drop=True)
)

metar_clouds_df = pd.concat(
    [
        metar_clouds_df.drop(columns=["clouds"]),
        pd.json_normalize(metar_clouds_df["clouds"])
    ],
    axis=1
)

metar_clouds_df.head()

  icaoId     obsTime cover  base
0   KEWR  1782170100   BKN   700
1   KEWR  1782170100   BKN  3000
2   KEWR  1782170100   OVC  8500
3   KJFK  1782168660   SCT   900
4   KJFK  1782168660   BKN  6500

OVC = Solid clouds

BKN = Broken clouds

SCT = Scattered clouds

base unit => ft

### SIGMET Fields

| Column | Meaning |
|----------|----------|
| hazard | Hazard type |
| validTimeFrom | Hazard start time |
| validTimeTo | Hazard end time |
| altitudeHi1 | Upper altitude limit |
| altitudeLow1 | Lower altitude limit |
| movementDir | Hazard movement direction |
| movementSpd | Hazard movement speed |
| severity | Hazard severity level |
| coords | Hazard polygon coordinates |
| airSigmetType | SIGMET/AIRMET category |
| rawAirSigmet | Raw bulletin text |
| creationTime | Bulletin creation timestamp |

In [34]:
sigmet_df.head()

,hazard,validTimeFrom,validTimeTo,altitudeHi1,altitudeLow1,movementDir,movementSpd,severity,coords,airSigmetType,rawAirSigmet,creationTime
0,CONVECTIVE,1782168900,1782176100,45000,None,270.0,35.0,5,"[{'lat': 46.144, 'lon': -106.289}, {'lat': 44....",SIGMET,WSUS33 KKCI 222255\nSIGW \nCONVECTIVE SIGMET 4...,2026-06-22T22:55:00.000Z
1,CONVECTIVE,1782168900,1782176100,45000,None,250.0,30.0,5,"[{'lat': 40.962, 'lon': -73.77}, {'lat': 40.25...",SIGMET,WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...,2026-06-22T22:55:00.000Z
2,CONVECTIVE,1782168900,1782176100,45000,None,280.0,30.0,5,"[{'lat': 36.392, 'lon': -85.917}, {'lat': 34.6...",SIGMET,WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...,2026-06-22T22:55:00.000Z
3,CONVECTIVE,1782168900,1782176100,45000,None,250.0,25.0,5,"[{'lat': 34.244, 'lon': -84.132}, {'lat': 33.0...",SIGMET,WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...,2026-06-22T22:55:00.000Z
4,CONVECTIVE,1782168900,1782176100,45000,None,250.0,20.0,5,"[{'lat': 32.922, 'lon': -84.844}, {'lat': 31.4...",SIGMET,WSUS31 KKCI 222255\nSIGE \nCONVECTIVE SIGMET 8...,2026-06-22T22:55:00.000Z

In [50]:
pd.json_normalize(sigmet_df["coords"].iloc[0])

      lat      lon
0  46.144 -106.289
1  44.839 -106.591
2  44.838 -107.769
3  46.061 -107.745
4  46.144 -106.289

In [59]:
sigmet_coords_df = (
    sigmet_df[
        [
            "hazard",
            "severity",
            "validTimeFrom",
            "validTimeTo",
            "altitudeLow1",
            "altitudeHi1",
            "movementDir",
            "movementSpd",
            "coords"
        ]
    ]
    .reset_index(names="sigmet_id")
    .explode("coords")
    .reset_index(drop=True)
)

sigmet_coords_df = pd.concat(
    [
        sigmet_coords_df.drop(columns=["coords"]),
        pd.json_normalize(sigmet_coords_df["coords"])
    ],
    axis=1
)

sigmet_coords_df.head()

,sigmet_id,hazard,severity,validTimeFrom,validTimeTo,altitudeLow1,altitudeHi1,movementDir,movementSpd,lat,lon
0,0,CONVECTIVE,5,1782168900,1782176100,None,45000,270.0,35.0,46.144,-106.289
1,0,CONVECTIVE,5,1782168900,1782176100,None,45000,270.0,35.0,44.839,-106.591
2,0,CONVECTIVE,5,1782168900,1782176100,None,45000,270.0,35.0,44.838,-107.769
3,0,CONVECTIVE,5,1782168900,1782176100,None,45000,270.0,35.0,46.061,-107.745
4,0,CONVECTIVE,5,1782168900,1782176100,None,45000,270.0,35.0,46.144,-106.289

The first and last lat/lon values are same.

### TAF Fields

| Column | Meaning |
|----------|----------|
| icaoId | Airport ICAO code |
| issueTime | Forecast issuance time |
| validTimeFrom | Forecast start time |
| validTimeTo | Forecast end time |
| fcsts | Forecast periods/details |
| rawTAF | Raw TAF bulletin |
| mostRecent | Indicates latest forecast |

In [35]:
taf_df.head()

,icaoId,issueTime,validTimeFrom,validTimeTo,fcsts,rawTAF,mostRecent
0,KLGA,2026-06-22T23:39:00.000Z,1782172800,1782280800,"[{'timeFrom': 1782172800, 'timeTo': 1782187200...",TAF KLGA 222339Z 2300/2406 03010KT 4SM -SHRA B...,1
1,KJFK,2026-06-22T23:39:00.000Z,1782172800,1782280800,"[{'timeFrom': 1782172800, 'timeTo': 1782187200...",TAF KJFK 222339Z 2300/2406 18010KT 6SM -SHRA B...,1
2,KEWR,2026-06-22T23:39:00.000Z,1782172800,1782280800,"[{'timeFrom': 1782172800, 'timeTo': 1782187200...",TAF KEWR 222339Z 2300/2406 07008KT 4SM -SHRA B...,1

In [44]:
taf_df["fcsts"].iloc[0]

[{'timeFrom': 1782172800,
  'timeTo': 1782187200,
  'timeBec': None,
  'fcstChange': None,
  'probability': None,
  'wdir': 30,
  'wspd': 10,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': 4,
  'altim': None,
  'vertVis': None,
  'wxString': '-SHRA BR',
  'notDecoded': None,
  'clouds': [{'cover': 'BKN', 'base': 700, 'type': None},
   {'cover': 'BKN', 'base': 900, 'type': None}],
  'icgTurb': [],
  'temp': []},
 {'timeFrom': 1782187200,
  'timeTo': 1782205200,
  'timeBec': None,
  'fcstChange': 'FM',
  'probability': None,
  'wdir': 180,
  'wspd': 9,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': 2,
  'altim': None,
  'vertVis': None,
  'wxString': '-SHRA BR',
  'notDecoded': None,
  'clouds': [{'cover': 'BKN', 'base': 300, 'type': None}],
  'icgTurb': [],
  'temp': []},
 {'timeFrom': 1782187200,
  'timeTo': 1782201600,
  'timeBec': None,
  'fcstChange': 'TEMPO',
  'probability': None,
  'wdir': None,
  'wspd': None,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': 1,
  'altim': None,
  'vertVis': None,
  'wxString': 'TSRA BR',
  'notDecoded': None,
  'clouds': [{'cover': 'OVC', 'base': 300, 'type': 'CB'}],
  'icgTurb': [],
  'temp': []},
 {'timeFrom': 1782205200,
  'timeTo': 1782226800,
  'timeBec': None,
  'fcstChange': 'FM',
  'probability': None,
  'wdir': 200,
  'wspd': 6,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': 3,
  'altim': None,
  'vertVis': None,
  'wxString': '-SHRA BR',
  'notDecoded': None,
  'clouds': [{'cover': 'BKN', 'base': 300, 'type': None}],
  'icgTurb': [],
  'temp': []},
 {'timeFrom': 1782216000,
  'timeTo': 1782226800,
  'timeBec': None,
  'fcstChange': 'PROB',
  'probability': 30,
  'wdir': None,
  'wspd': None,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': 1,
  'altim': None,
  'vertVis': None,
  'wxString': '-SHRA BR',
  'notDecoded': None,
  'clouds': [{'cover': 'OVC', 'base': 200, 'type': None}],
  'icgTurb': [],
  'temp': []},
 {'timeFrom': 1782226800,
  'timeTo': 1782241200,
  'timeBec': None,
  'fcstChange': 'FM',
  'probability': None,
  'wdir': 330,
  'wspd': 8,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': 4,
  'altim': None,
  'vertVis': None,
  'wxString': '-SHRA BR',
  'notDecoded': None,
  'clouds': [{'cover': 'BKN', 'base': 300, 'type': None}],
  'icgTurb': [],
  'temp': []},
 {'timeFrom': 1782241200,
  'timeTo': 1782259200,
  'timeBec': None,
  'fcstChange': 'FM',
  'probability': None,
  'wdir': 350,
  'wspd': 10,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': 5,
  'altim': None,
  'vertVis': None,
  'wxString': '-SHRA BR',
  'notDecoded': None,
  'clouds': [{'cover': 'OVC', 'base': 700, 'type': None}],
  'icgTurb': [],
  'temp': []},
 {'timeFrom': 1782259200,
  'timeTo': 1782280800,
  'timeBec': None,
  'fcstChange': 'FM',
  'probability': None,
  'wdir': 330,
  'wspd': 8,
  'wgst': None,
  'wshearHgt': None,
  'wshearDir': None,
  'wshearSpd': None,
  'visib': '6+',
  'altim': None,
  'vertVis': None,
  'wxString': None,
  'notDecoded': None,
  'clouds': [{'cover': 'SCT', 'base': 7000, 'type': None}],
  'icgTurb': [],
  'temp': []}]

In [45]:
pd.json_normalize(taf_df["fcsts"].iloc[0])

,timeFrom,timeTo,timeBec,fcstChange,probability,wdir,wspd,wgst,wshearHgt,wshearDir,wshearSpd,visib,altim,vertVis,wxString,notDecoded,clouds,icgTurb,temp
0,1782172800,1782187200,None,NaN,NaN,30.0,10.0,None,None,None,None,4,None,None,-SHRA BR,None,"[{'cover': 'BKN', 'base': 700, 'type': None}, ...",[],[]
1,1782187200,1782205200,None,FM,NaN,180.0,9.0,None,None,None,None,2,None,None,-SHRA BR,None,"[{'cover': 'BKN', 'base': 300, 'type': None}]",[],[]
2,1782187200,1782201600,None,TEMPO,NaN,NaN,NaN,None,None,None,None,1,None,None,TSRA BR,None,"[{'cover': 'OVC', 'base': 300, 'type': 'CB'}]",[],[]
3,1782205200,1782226800,None,FM,NaN,200.0,6.0,None,None,None,None,3,None,None,-SHRA BR,None,"[{'cover': 'BKN', 'base': 300, 'type': None}]",[],[]
4,1782216000,1782226800,None,PROB,30.0,NaN,NaN,None,None,None,None,1,None,None,-SHRA BR,None,"[{'cover': 'OVC', 'base': 200, 'type': None}]",[],[]
5,1782226800,1782241200,None,FM,NaN,330.0,8.0,None,None,None,None,4,None,None,-SHRA BR,None,"[{'cover': 'BKN', 'base': 300, 'type': None}]",[],[]
6,1782241200,1782259200,None,FM,NaN,350.0,10.0,None,None,None,None,5,None,None,-SHRA BR,None,"[{'cover': 'OVC', 'base': 700, 'type': None}]",[],[]
7,1782259200,1782280800,None,FM,NaN,330.0,8.0,None,None,None,None,6+,None,None,NaN,None,"[{'cover': 'SCT', 'base': 7000, 'type': None}]",[],[]

In [ ]:
taf_fcsts_df = (
    taf_df[["icaoId", "issueTime", "validTimeFrom", "validTimeTo", "fcsts"]]
    .explode("fcsts")
    .reset_index(drop=True)
)

taf_fcsts_df = pd.concat(
    [
        taf_fcsts_df.drop(columns=["fcsts"]),
        pd.json_normalize(taf_fcsts_df["fcsts"])
    ],
    axis=1
)

taf_fcsts_df.head()

,icaoId,issueTime,validTimeFrom,validTimeTo,timeFrom,timeTo,timeBec,fcstChange,probability,wdir,...,wshearDir,wshearSpd,visib,altim,vertVis,wxString,notDecoded,clouds,icgTurb,temp
0,KLGA,2026-06-22T23:39:00.000Z,1782172800,1782280800,1782172800,1782187200,None,NaN,NaN,30.0,...,None,None,4,None,None,-SHRA BR,None,"[{'cover': 'BKN', 'base': 700, 'type': None}, ...",[],[]
1,KLGA,2026-06-22T23:39:00.000Z,1782172800,1782280800,1782187200,1782205200,None,FM,NaN,180.0,...,None,None,2,None,None,-SHRA BR,None,"[{'cover': 'BKN', 'base': 300, 'type': None}]",[],[]
2,KLGA,2026-06-22T23:39:00.000Z,1782172800,1782280800,1782187200,1782201600,None,TEMPO,NaN,NaN,...,None,None,1,None,None,TSRA BR,None,"[{'cover': 'OVC', 'base': 300, 'type': 'CB'}]",[],[]
3,KLGA,2026-06-22T23:39:00.000Z,1782172800,1782280800,1782205200,1782226800,None,FM,NaN,200.0,...,None,None,3,None,None,-SHRA BR,None,"[{'cover': 'BKN', 'base': 300, 'type': None}]",[],[]
4,KLGA,2026-06-22T23:39:00.000Z,1782172800,1782280800,1782216000,1782226800,None,PROB,30.0,NaN,...,None,None,1,None,None,-SHRA BR,None,"[{'cover': 'OVC', 'base': 200, 'type': None}]",[],[]

In [48]:
taf_fcsts_df.columns

Index(['icaoId', 'issueTime', 'validTimeFrom', 'validTimeTo', 'timeFrom',
       'timeTo', 'timeBec', 'fcstChange', 'probability', 'wdir', 'wspd',
       'wgst', 'wshearHgt', 'wshearDir', 'wshearSpd', 'visib', 'altim',
       'vertVis', 'wxString', 'notDecoded', 'clouds', 'icgTurb', 'temp'],
      dtype='str')

FM = FROM this time onward, replace the previous forecast.

TEMPO = Temporary conditions may occur.

PROB = 30% chance this happens.

| API     | Total Fields | Important Fields |
| ------- | ------------ | ---------------- |
| OpenSky | 17           | 10               |
| METAR   | 22           | 10               |
| SIGMET  | 19           | 9                |
| TAF     | 15           | 5 (+ fcsts)      |